spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loandb
    username: root
    password: # leave blank if no password is needed
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

