spring:
  datasource:
    url: {jdbc:mysql://localhost:3306/loandb} { username:root { password: { driver-class-name: com.mysql.ch.jdbc.Driver, initialization-mode: always } } }


  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
